name: Install miniconda

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    steps:
      - name: install miniconda and create a virtual environment with Python ${{matrix.python_version}}
        run: |
             curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh --output $HOME/miniconda.sh
             bash ~/miniconda.sh -b -p $HOME/miniconda
             eval "$($HOME/miniconda/bin/conda shell.bash hook)"
             conda create --name my-env python=${{matrix.python-version}}
